version: '3'
services:
  nginx:
    build:
      context: ./nginx
    container_name: rails_nginx
    volumes:
      - ./nginx/development.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    links:
      - rails
  rails:
    build:
      context: ./rails
    container_name: rails_rails
    command: bash /docker-entrypoint.sh
    volumes:
      - ../rails-source:/rails-app:cached
    links:
      - mysql
  mysql:
    build:
      context: ./mysql
    container_name: rails_mysql
    volumes:
      - ./data-volumes/mysql/var-lib-mysql:/var/lib/mysql:cached
    env_file: .env
    ports:
      - "3306:3306"